name: deploy website
on:
  push:
    branches: [main]
    paths:
      - "packages/website/**"
      - "reacord/library/**/*.{ts,tsx}"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
