name: main

on:
  push:
    branches: [main]
  pull_request:

env:
  TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
  TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
  TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}

jobs:
  run-commands:
    strategy:
      fail-fast: false
      matrix:
        command:
          # if these run in the same process, it dies,
          # so we test them separate
          - name: test reacord
            run: pnpm test -C packages/reacord
          - name: test website
            run: pnpm test -C packages/website
          - name: build
            run: pnpm build --recursive
          - name: lint
            run: pnpm lint
          - name: typecheck
            run: pnpm typecheck --parallel
    name: ${{ matrix.command.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "16"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: ${{ matrix.command.run }}
